import {
  AdminProject,
  AdminService,
  AdminPricingPlan,
  AdminMessage,
  AdminWhatsAppConfig,
  AdminMediaAsset,
  AdminTestimonial,
  AdminTeamMember,
  AdminArticle,
  AdminNotification,
  AdminSettings,
  AdminStudioSettings,
  AdminUser,
} from './types';

export const INITIAL_ADMIN_USER: AdminUser = {
  name: 'Marcus Vance',
  email: 'admin@aura-ai.studio',
  role: 'Executive Creative Director',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  twoFactorEnabled: true,
  lastLogin: 'Today at 08:42 AM',
};

export const INITIAL_PROJECTS: AdminProject[] = [
  {
    id: 'proj-1',
    title: 'Kira Luxe Fragrance — Liquid Gold Specular',
    slug: 'kira-luxe-fragrance-liquid-gold',
    client: 'Kira Parfums Paris',
    category: 'Product Commercial',
    status: 'published',
    isFeatured: true,
    thumbnail: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration: '30s',
    resolution: '4K Cinema 60fps',
    year: '2026',
    views: 48920,
    likes: 3410,
    shortDescription: 'High-end AI product commercial with photorealistic liquid physics and studio caustics.',
    fullDescription: 'Crafted with multi-camera LoRA checkpoints, prompt-guided volumetric lighting, and DaVinci Resolve color timing. Achieved zero artifacts on micro-fluid splashes.',
    toolsUsed: ['Runway Gen-3 Alpha', 'Midjourney v6.1', 'DaVinci Resolve Studio', 'ElevenLabs Pro'],
    results: '+340% increase in pre-order conversion; 2.4M organic impressions across Instagram & YouTube.',
    clientTestimonial: {
      quote: 'AURA AI delivered cinema-grade product visuals in 5 days that usually take 6 weeks of physical studio production.',
      author: 'Élodie Laurent',
      role: 'Global VP Marketing, Kira Parfums',
    },
    seoTitle: 'Kira Parfums Commercial | AI Video Production by AURA AI',
    seoDescription: 'Explore the 4K AI video commercial produced for Kira Parfums featuring synthetic fluid optics.',
    createdAt: '2026-08-01',
    updatedAt: '2026-08-14',
  },
  {
    id: 'proj-2',
    title: 'Neo-Tokyo Cyber Runner — Season 04 Reveal',
    slug: 'neo-tokyo-cyber-runner',
    client: 'Velentis Footwear Corp',
    category: 'Cinematic Storytelling',
    status: 'published',
    isFeatured: true,
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration: '60s',
    resolution: '4K UHD',
    year: '2026',
    views: 112400,
    likes: 8900,
    shortDescription: 'High-speed synthetic tracking shots through neon-drenched rainy Tokyo streets.',
    fullDescription: 'Combines stylized character consistency, dynamic camera transitions, custom synthwave sound design, and kinetic typography for a sneaker drop.',
    toolsUsed: ['Kling AI 1.5', 'Sora 4K Engine', 'Adobe Premiere Pro', 'Splice Audio'],
    results: 'Sold out launch inventory within 48 minutes of reel release.',
    clientTestimonial: {
      quote: 'The energy and fluid motion they created blew our internal creative team away.',
      author: 'Daisuke Takahashi',
      role: 'Head of Brand, Velentis',
    },
    seoTitle: 'Velentis Cyber Runner Commercial | AURA AI Production',
    seoDescription: 'Watch the cinematic AI sneaker spot engineered with multi-camera continuous motion.',
    createdAt: '2026-07-28',
    updatedAt: '2026-08-10',
  },
  {
    id: 'proj-3',
    title: 'Chronos Swiss Horology — Tourbillon Micro-Macro',
    slug: 'chronos-swiss-horology',
    client: 'Chronos Genève',
    category: 'Product Commercial',
    status: 'published',
    isFeatured: true,
    thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration: '45s',
    resolution: '4K Cinema 60fps',
    year: '2026',
    views: 31500,
    likes: 2120,
    shortDescription: 'Macro gear mechanics and sapphire crystal refraction for luxury timepieces.',
    fullDescription: 'Rendered with extreme depth of field, mechanical precision prompts, and real acoustic ticking audio Foley synthesis.',
    toolsUsed: ['Midjourney v6', 'Runway Gen-3', 'Logic Pro X', 'DaVinci Resolve'],
    results: 'Featured in Geneva Watch Week 2026 opening keynote.',
    seoTitle: 'Chronos Swiss Watch AI Commercial | AURA AI Studio',
    seoDescription: 'Ultra-macro generative AI visuals showcasing mechanical luxury watch movements.',
    createdAt: '2026-07-15',
    updatedAt: '2026-08-05',
  },
  {
    id: 'proj-4',
    title: 'Apex GT Hypercar — Alpine Mountain Ascent',
    slug: 'apex-gt-hypercar-ascent',
    client: 'Apex Automotive Munich',
    category: 'Automotive',
    status: 'published',
    isFeatured: false,
    thumbnail: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration: '30s',
    resolution: '4K UHD',
    year: '2026',
    views: 64200,
    likes: 4700,
    shortDescription: 'Alpine twist drift tracking shots with synthetic drone passes and tyre smoke physics.',
    fullDescription: 'Seamless drone cinematography generated without expensive helicopter permits or road closures.',
    toolsUsed: ['Runway Gen-3', 'Luma Dream Machine', 'After Effects', 'Pro Tools'],
    results: 'Saved $85,000 in physical production permits and crew logistics.',
    seoTitle: 'Apex GT Hypercar Commercial | AURA AI',
    seoDescription: 'Automotive AI commercial production with hyper-realistic high-speed vehicle dynamics.',
    createdAt: '2026-07-02',
    updatedAt: '2026-07-29',
  },
  {
    id: 'proj-5',
    title: 'Aethel Luxury Silk — Autumn Lookbook Film',
    slug: 'aethel-luxury-silk-autumn',
    client: 'Maison Aethel',
    category: 'Fashion & Luxury',
    status: 'draft',
    isFeatured: false,
    thumbnail: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration: '20s',
    resolution: '4K Vertical 9:16',
    year: '2026',
    views: 0,
    likes: 0,
    shortDescription: 'Slow-motion silk fabric drapery and ethereal studio lighting lookbook.',
    fullDescription: 'In active review with the client creative director. Final render queue processing on node 04.',
    toolsUsed: ['Midjourney v6.1', 'Runway Gen-3 Alpha', 'Color Finale 2'],
    results: 'Pending public campaign launch September 2026.',
    seoTitle: 'Maison Aethel Lookbook | AURA AI',
    seoDescription: 'Fashion lookbook generated with advanced generative AI textile simulations.',
    createdAt: '2026-08-15',
    updatedAt: '2026-08-18',
  },
];

export const INITIAL_SERVICES: AdminService[] = [
  {
    id: 'serv-1',
    name: 'AI Video Commercials & Product Ads',
    icon: 'Film',
    category: 'Core Production',
    shortDescription: 'Cinema-grade 4K commercials for luxury products, consumer brands, and tech hardware.',
    detailedDescription: 'Full-spectrum video production leveraging custom diffusion pipelines, precision prompt engineering, fluid optics, and human directorial polish. Replaces $50k+ physical sets with flawless synthetic cinematography.',
    features: [
      '30s – 60s 4K Ultra-HD Master Video',
      '9:16 Vertical (Reels/TikTok) + 16:9 Cinema formats',
      'Photorealistic fluid, particle & specular physics',
      'Bespoke studio lighting & caustics simulation',
      'Professional sound design & licensed audio master',
      'Turnaround in 3 to 7 business days',
    ],
    startingPrice: '₹35,000 / spot',
    ctaText: 'Book Commercial Production',
    displayOrder: 1,
    isFeatured: true,
    isActive: true,
    deliverables: '4K ProRes Master, H.264 Web Cuts, Social Aspect Ratios',
    turnaround: '3–5 Days',
  },
  {
    id: 'serv-2',
    name: 'Cinematic Storytelling & Brand Films',
    icon: 'Sparkles',
    category: 'Brand Narratives',
    shortDescription: 'High-concept visual narratives, founder stories, and mood films that captivate audiences.',
    detailedDescription: 'Engaging, emotive video storytelling combining custom character consistency, multi-scene continuity, atmospheric grade, and synthetic voiceover narration by top voice actors.',
    features: [
      'Multi-scene continuous character & location tracking',
      'Scriptwriting & creative treatment development',
      'Neural synthetic voiceover & cinematic scoring',
      'Color grading in DaVinci Resolve Studio',
      'Social media teaser cutdowns included',
    ],
    startingPrice: '₹60,000 / film',
    ctaText: 'Commission Brand Film',
    displayOrder: 2,
    isFeatured: true,
    isActive: true,
    deliverables: 'Master 4K Video, 3 Social Cuts, Raw 4K Stills',
    turnaround: '5–8 Days',
  },
  {
    id: 'serv-3',
    name: '3D Motion & VFX Compositing',
    icon: 'Layers',
    category: 'Post-Production',
    shortDescription: 'Complex abstract dynamics, kinetic typography, and surreal visual effects.',
    detailedDescription: 'Bridging generative AI with traditional 3D CGI and compositing tools for high-precision brand systems, kinetic logos, and explosive product reveals.',
    features: [
      'Kinetic typography & 3D title design',
      'Procedural fluid, smoke & particle dynamics',
      'Alpha channel transparent video deliverables',
      'Seamless product rotoscoping and background replacement',
    ],
    startingPrice: '₹25,000 / asset',
    ctaText: 'Request VFX Breakdown',
    displayOrder: 3,
    isFeatured: false,
    isActive: true,
    deliverables: 'Transparent Alpha MOV, 4K Master Video',
    turnaround: '3–4 Days',
  },
  {
    id: 'serv-4',
    name: 'AI Product Photography & Still Posters',
    icon: 'Camera',
    category: 'Still Imagery',
    shortDescription: 'Hyper-detailed studio product renders, billboard key visuals, and eCommerce sets.',
    detailedDescription: 'Studio-quality product imagery placed in infinite synthetic environments without shipping products or booking studios.',
    features: [
      '8K Ultra-High-Resolution Still Renders',
      'Packshot variations (Minimalist, Lifestyle, Dramatic)',
      'High-resolution print ready CMYK files',
      'Layered PSD with editable mask channels',
    ],
    startingPrice: '₹500 / image',
    ctaText: 'Order Product Imagery',
    displayOrder: 4,
    isFeatured: false,
    isActive: true,
    deliverables: '8K TIFF, CMYK Print PSD, WebP',
    turnaround: '24–48 Hours',
  },
];

export const INITIAL_PRICING_PLANS: AdminPricingPlan[] = [
  {
    id: 'tier-starter',
    name: 'Starter Spot',
    tagline: 'Ideal for D2C brands, social reels & fast product launches',
    price: '₹25,000',
    billingLabel: 'per commercial',
    description: 'A punchy 15–20 second 4K AI product commercial tailored for high-converting Instagram Reels and TikTok ads.',
    features: [
      '15–20s 4K Ultra-HD AI Commercial',
      '9:16 Vertical + 16:9 Horizontal versions',
      'AI Scriptwriting & Creative Treatment',
      'Photorealistic Studio Lighting & Particle Effects',
      'Sound Design & Commercial Licensed Music',
      '2 Iterative Revision Rounds',
      'Delivery in 3 Business Days',
    ],
    turnaroundTime: '3 Days',
    ctaText: 'Get Starter Spot',
    isFeatured: false,
    displayOrder: 1,
    isActive: true,
    badge: 'Fast Turnaround',
  },
  {
    id: 'tier-growth',
    name: 'Growth Studio',
    tagline: 'Our most popular tier for luxury brands and scaleups',
    price: '₹45,000',
    billingLabel: 'per commercial',
    description: 'Full 30-second cinema-grade commercial with complex fluid mechanics, custom sound design, and multi-angle scene choreography.',
    features: [
      '30s 4K Cinema Master Commercial',
      'Full Multi-Format Suite (9:16, 16:9, 1:1, 4:5)',
      'Deep Brand Consistency & Color Match',
      'Complex Fluid Dynamics & Specular Optics',
      'Neural Voiceover in 20+ Languages',
      '3 Poster Stills (8K Resolution for Ads)',
      'Priority Render Queue',
      '3 Iterative Revision Rounds',
      'Delivery in 4–5 Business Days',
    ],
    turnaroundTime: '4–5 Days',
    ctaText: 'Launch Growth Spot',
    isFeatured: true,
    displayOrder: 2,
    isActive: true,
    badge: 'Most Popular',
  },
  {
    id: 'tier-enterprise',
    name: 'Cinema Enterprise',
    tagline: 'For global brands needing bespoke 60s films & ongoing campaign suites',
    price: '₹85,000',
    billingLabel: 'per campaign',
    description: 'Comprehensive 60-second narrative brand film with episodic social cuts, dedicated creative director, and raw 4K asset delivery.',
    features: [
      '60s Master Film + (3x) 15s Episodic Cutdowns',
      'Custom LoRA Checkpoint Training for Your Exact Product',
      'Dedicated Creative Director & Prompt Architect',
      'Unlimited Scene Complexity & Dynamic Camera Moves',
      'Orchestrated Foley & Spatial Audio Master',
      '10 High-Res Key Visual Posters (8K CMYK)',
      'Full Commercial Buyout & IP Ownership',
      'Unlimited Revisions during review window',
      'Delivery in 6–8 Business Days',
    ],
    turnaroundTime: '6–8 Days',
    ctaText: 'Commission Enterprise Suite',
    isFeatured: false,
    displayOrder: 3,
    isActive: true,
    badge: 'Full Campaign Suite',
  },
];

export const INITIAL_MESSAGES: AdminMessage[] = [
  {
    id: 'msg-101',
    name: 'Élodie Laurent',
    email: 'e.laurent@kira-parfums.com',
    phone: '+33 6 42 91 88 20',
    company: 'Kira Parfums Paris',
    subject: 'Autumn Fragrance Launch — 3x 4K Spots Campaign',
    message: 'Hello AURA AI team, we loved your recent work on the liquid gold spot. We are preparing our Autumn fragrance collection and would like to commission three 30s 4K video ads for global social distribution. Can we schedule a brief creative kickoff call?',
    budget: '₹1,50,000 – ₹2,50,000',
    timeline: 'Need delivery by Sept 15th',
    serviceCategory: 'AI Video Commercials',
    date: '2026-08-19',
    time: '02:45 PM',
    status: 'new',
    replies: [],
  },
  {
    id: 'msg-102',
    name: 'Rohit Shenoy',
    email: 'rohit@zenithbeverages.in',
    phone: '+91 98201 44512',
    company: 'Zenith Sparkling Beverages',
    subject: 'Commercial Video for New Sparkling Citrus Line',
    message: 'Looking for a dynamic commercial highlighting carbonation splash physics and ice condensation on our aluminium can cans. Is a 3-day turnaround possible under the Growth Studio plan?',
    budget: '₹45,000',
    timeline: 'Within 1 week',
    serviceCategory: 'Product Ads',
    date: '2026-08-18',
    time: '11:15 AM',
    status: 'read',
    replies: [
      {
        id: 'rep-1',
        sender: 'admin',
        message: 'Hi Rohit, thanks for reaching out! Yes, we can certainly execute the sparkling splash dynamics within 4 business days. I have sent over our asset onboarding deck to your email.',
        timestamp: '2026-08-18 11:40 AM',
      },
    ],
  },
  {
    id: 'msg-103',
    name: 'Alexander Brandt',
    email: 'alex@brandt-watches.ch',
    phone: '+41 79 320 44 19',
    company: 'Brandt Horology',
    subject: 'Enquiry for Watch Tourbillon 3D AI Animation',
    message: 'We require ultra-macro generative video showcasing our titanium tourbillon cage with accurate reflection of studio lightboxes. Please provide pricing for 2 spots.',
    budget: '₹85,000',
    timeline: 'End of August',
    serviceCategory: 'AI Video Commercials',
    date: '2026-08-17',
    time: '04:30 PM',
    status: 'replied',
    replies: [
      {
        id: 'rep-2',
        sender: 'admin',
        message: 'Hello Alexander, we have shared a proposal for two 4K spots along with technical specs for 3D asset handoff. Looking forward to your review.',
        timestamp: '2026-08-17 05:10 PM',
      },
    ],
  },
  {
    id: 'msg-104',
    name: 'Maya Lin',
    email: 'maya@velentis.com',
    phone: '+1 415 892 0119',
    company: 'Velentis Footwear',
    subject: 'Follow-up on Season 04 Sneaker Campaign Assets',
    message: 'The final render files received yesterday looked fantastic. We are confirming the wire transfer and would like to reserve render capacity for our Q4 winter boot reveal.',
    budget: '₹1,20,000',
    timeline: 'October 2026',
    serviceCategory: 'Cinematic Storytelling',
    date: '2026-08-15',
    time: '09:20 AM',
    status: 'archived',
    replies: [],
  },
];

export const INITIAL_WHATSAPP_CONFIG: AdminWhatsAppConfig = {
  phoneNumber: '+91 94002 96191',
  isEnabled: true,
  defaultGreeting: 'Hello! Welcome to AURA AI Studio. Redefining Commercials with AI.',
  preFilledPrompt: 'Hi AURA AI team! I am interested in creating an AI video commercial for my brand. Let us discuss details.',
  ctaText: 'Chat on WhatsApp',
  buttonVisibility: {
    mobile: true,
    desktop: true,
  },
  businessHours: {
    enabled: true,
    start: '09:00',
    end: '21:00',
    timezone: 'Asia/Kolkata (IST)',
    offlineMessage: 'Thanks for reaching out! Our production studio is currently offline. We will reply to your WhatsApp message first thing at 9:00 AM IST.',
  },
  inquiryLogs: [
    {
      id: 'wa-1',
      name: 'Aditya Mehta',
      phone: '+91 98192 10928',
      timestamp: 'Today, 10:14 AM',
      topic: 'Perfume commercial rate inquiry',
      sourcePage: 'Homepage / Pricing',
    },
    {
      id: 'wa-2',
      name: 'Sarah Jenkins',
      phone: '+44 7700 900142',
      timestamp: 'Yesterday, 07:30 PM',
      topic: 'Fashion lookbook video timeline',
      sourcePage: 'Works / Kira Parfums',
    },
    {
      id: 'wa-3',
      name: 'Karan Verma',
      phone: '+91 99401 22841',
      timestamp: '16 Aug, 03:15 PM',
      topic: 'Aluminium can beverage 3D splash spot',
      sourcePage: 'Services / AI Commercials',
    },
  ],
};

export const INITIAL_MEDIA_ASSETS: AdminMediaAsset[] = [
  {
    id: 'med-1',
    name: 'Kira_Fragrance_Fluid_Caustics_4K.mp4',
    type: 'video',
    url: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&auto=format&fit=crop&q=80',
    size: '148.4 MB',
    resolution: '3840x2160',
    duration: '00:30',
    tags: ['Perfume', 'Fluid Optics', '4K Master', 'Luxury'],
    uploadedAt: '2026-08-10',
    usedInProjects: ['Kira Luxe Fragrance'],
  },
  {
    id: 'med-2',
    name: 'Cyber_Sneaker_Tokyo_Rain_9x16.mp4',
    type: 'video',
    url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&auto=format&fit=crop&q=80',
    size: '89.2 MB',
    resolution: '1080x1920',
    duration: '00:60',
    tags: ['Sneakers', 'Cyberpunk', '9:16 Vertical', 'Reels'],
    uploadedAt: '2026-08-08',
    usedInProjects: ['Neo-Tokyo Cyber Runner'],
  },
  {
    id: 'med-3',
    name: 'Chronos_Watch_Tourbillon_Macro.mp4',
    type: 'video',
    url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&auto=format&fit=crop&q=80',
    size: '112.0 MB',
    resolution: '3840x2160',
    duration: '00:45',
    tags: ['Horology', 'Macro', 'Titanium', '4K'],
    uploadedAt: '2026-08-05',
    usedInProjects: ['Chronos Swiss Horology'],
  },
  {
    id: 'med-4',
    name: 'AURA_Brand_KeyVisual_Poster_8K.png',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    size: '42.8 MB',
    resolution: '7680x4320',
    tags: ['Key Visual', 'Billboard', '8K Still', 'Branding'],
    uploadedAt: '2026-08-01',
    usedInProjects: ['Website Hero', 'Print Brochure'],
  },
];

export const INITIAL_TESTIMONIALS: AdminTestimonial[] = [
  {
    id: 'test-1',
    clientName: 'Élodie Laurent',
    company: 'Kira Parfums Paris',
    position: 'Global VP Marketing',
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    testimonial: 'AURA AI delivered cinema-grade product visuals in 5 days that usually take 6 weeks of physical studio production. The fluid physics and lighting are indiscernible from live action.',
    rating: 5,
    projectTag: 'Kira Luxe Fragrance',
    isFeatured: true,
    displayOrder: 1,
    isPublished: true,
    dateAdded: '2026-08-12',
  },
  {
    id: 'test-2',
    clientName: 'Daisuke Takahashi',
    company: 'Velentis Footwear Corp',
    position: 'Head of Brand & Media',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    testimonial: 'The dynamic neon tracking shots created for our sneaker drop generated over 2.4 million organic views and sold out our initial inventory in under an hour.',
    rating: 5,
    projectTag: 'Neo-Tokyo Cyber Runner',
    isFeatured: true,
    displayOrder: 2,
    isPublished: true,
    dateAdded: '2026-08-09',
  },
  {
    id: 'test-3',
    clientName: 'Julian Vance',
    company: 'Chronos Horology',
    position: 'Creative Director',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    testimonial: 'Macro sapphire glass refraction and micro gear motion were flawless. We avoided high-risk handling of rare prototype movements while obtaining 4K cinema assets.',
    rating: 5,
    projectTag: 'Chronos Swiss Watch',
    isFeatured: false,
    displayOrder: 3,
    isPublished: true,
    dateAdded: '2026-08-02',
  },
];

export const INITIAL_TEAM_MEMBERS: AdminTeamMember[] = [
  {
    id: 'team-1',
    name: 'Marcus Vance',
    role: 'Founder & Executive Creative Director',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    bio: 'Former luxury brand film director. Pioneering prompt-to-cinema diffusion workflows and generative studio lighting pipelines.',
    socials: {
      twitter: 'https://twitter.com',
      linkedin: 'https://linkedin.com',
      instagram: 'https://instagram.com',
    },
    specialties: ['Art Direction', 'Custom LoRA Training', 'Color Grading'],
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'team-2',
    name: 'Elena Rostova',
    role: 'Lead AI Prompt Architect & VFX Supervisor',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    bio: 'Specialized in fluid dynamics, specular caustics, and multi-checkpoint temporal coherence across 4K generation nodes.',
    socials: {
      linkedin: 'https://linkedin.com',
      github: 'https://github.com',
    },
    specialties: ['Temporal Coherence', 'Fluid Optics', 'DaVinci Resolve Studio'],
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'team-3',
    name: 'Devon Wright',
    role: 'Senior Sound Designer & Foley Composer',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    bio: 'Crafting spatial audio, dynamic acoustic Foley, and high-impact cinematic synthesizer scores that bring synthetic motion to life.',
    socials: {
      instagram: 'https://instagram.com',
      twitter: 'https://twitter.com',
    },
    specialties: ['Spatial Audio', 'Foley Synthesis', 'Logic Pro X'],
    displayOrder: 3,
    isActive: true,
  },
];

export const INITIAL_ARTICLES: AdminArticle[] = [
  {
    id: 'art-1',
    title: 'Achieving Zero-Artifact Fluid Caustics in 4K AI Commercials',
    slug: 'zero-artifact-fluid-caustics-ai-commercials',
    category: 'Production Breakdown',
    excerpt: 'How we engineered a proprietary lighting checkpoint to eliminate flickering in luxury perfume commercials.',
    content: 'Liquid dynamics in generative AI video have historically struggled with temporal flickering. Here is our step-by-step methodology using multi-pass latent guidance and custom LoRA weights in DaVinci Resolve.',
    coverImage: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop&q=80',
    author: 'Elena Rostova',
    readTime: '6 min read',
    publishedAt: '2026-08-11',
    status: 'published',
    views: 4230,
    tags: ['AI Commercials', 'Fluid Optics', 'VFX Pipeline'],
  },
  {
    id: 'art-2',
    title: 'Why D2C Brands Are Replacing Physical Studio Shoots with AURA AI',
    slug: 'd2c-brands-replacing-physical-shoots',
    category: 'Industry Insights',
    excerpt: 'Comparing the unit economics and speed-to-market of physical set rentals versus generative AI production.',
    content: 'Traditional 30-second commercial production averages $45,000 to $120,000 and 6 to 8 weeks. Learn how high-growth scaleups ship 3x more creative variations at 80% lower cost.',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    author: 'Marcus Vance',
    readTime: '4 min read',
    publishedAt: '2026-08-04',
    status: 'published',
    views: 8910,
    tags: ['ROI', 'D2C Marketing', 'Production Speed'],
  },
];

export const INITIAL_NOTIFICATIONS: AdminNotification[] = [
  {
    id: 'notif-1',
    title: 'New High-Value Project Inquiry',
    description: 'Élodie Laurent from Kira Parfums requested a kickoff for 3x 4K commercial spots.',
    category: 'enquiry',
    timestamp: '15 mins ago',
    isRead: false,
    actionUrl: 'Messages',
  },
  {
    id: 'notif-2',
    title: 'WhatsApp Lead Captured',
    description: 'Aditya Mehta initiated a chat regarding perfume commercial pricing.',
    category: 'whatsapp',
    timestamp: '2 hours ago',
    isRead: false,
    actionUrl: 'WhatsApp',
  },
  {
    id: 'notif-3',
    title: '4K Render Batch Completed',
    description: 'Neo-Tokyo Cyber Runner 9:16 vertical cuts finished rendering on Node 02.',
    category: 'project',
    timestamp: '4 hours ago',
    isRead: true,
    actionUrl: 'Projects',
  },
  {
    id: 'notif-4',
    title: 'Security Notice',
    description: 'Admin login verified from authenticated production IP session.',
    category: 'security',
    timestamp: 'Yesterday',
    isRead: true,
    actionUrl: 'Settings',
  },
];

export const INITIAL_SETTINGS: AdminStudioSettings = {
  studioName: 'AURA AI Studio',
  tagline: 'Redefining Commercials with AI',
  primaryEmail: 'contact@aura-ai.studio',
  primaryPhone: '+91 94002 96191',
  location: 'AURA AI Productions, Creative Quarter, Bandra West, Mumbai, India',
  currency: 'INR (₹)',
  primaryColor: '#0C0E12',
  accentColor: '#B15F2C',
  seoTitle: 'AURA AI | High-End AI Video Commercial Production',
  seoDescription: 'Redefining commercial production with artificial intelligence. 4K product ads, cinematic storytelling, and visual effects for luxury and scaleup brands.',
  ogImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200',
};

// Aliases for component imports
export const initialMockAdminUser = INITIAL_ADMIN_USER;
export const initialMockProjects = INITIAL_PROJECTS;
export const initialMockServices = INITIAL_SERVICES;
export const initialMockPricingPlans = INITIAL_PRICING_PLANS;
export const initialMockMessages = INITIAL_MESSAGES;
export const initialMockWhatsAppConfig = INITIAL_WHATSAPP_CONFIG;
export const initialMockMediaAssets = INITIAL_MEDIA_ASSETS;
export const initialMockTestimonials = INITIAL_TESTIMONIALS;
export const INITIAL_TEAM = INITIAL_TEAM_MEMBERS;
export const initialMockTeam = INITIAL_TEAM_MEMBERS;
export const initialMockArticles = INITIAL_ARTICLES;
export const initialMockNotifications = INITIAL_NOTIFICATIONS;
export const initialMockStudioSettings = INITIAL_SETTINGS;

